repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.3
    hooks:
      - id: gitleaks
        args: ["--config", ".gitleaks.toml", "--verbose"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
